set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "TaskMonitor Interface Library")
set(CPACK_VERBATIM_VARIABLES YES)

#Set each packet to be packaged into an RPM packet
set(CPACK_COMPONENTS_GROUPING ONE_PER_GROUP)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/packages")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_VENDOR "Alin Popa")
set(CPACK_PACKAGE_CONTACT "alin.popa@fxdata.ro")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_COMPONENTS_ALL bin dev)

# RPM
set(CPACK_RPM_PACKAGE_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_RPM_BIN_FILE_NAME "${PROJECT_NAME}-bin-${CPACK_RPM_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}.rpm")
set(CPACK_RPM_DEV_FILE_NAME "${PROJECT_NAME}-dev-${CPACK_RPM_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}.rpm")
set(CPACK_RPM_DEBUGINFO_PACKAGE OFF)
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_CHANGELOG_FILE "${CMAKE_SOURCE_DIR}/CHANGELOG")
set(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION_SUMMARY})
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_BIN_PACKAGE_REQUIRES "protobuf >= 3.14.0")
set(CPACK_RPM_DEV_PACKAGE_REQUIRES "${PROJECT_NAME}-bin = ${CPACK_RPM_PACKAGE_VERSION}, protobuf >= 3.14.0, protobuf-devel >= 3.14.0, protobuf-compiler >= 3.14.0")
list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/sbin")
set(CPACK_RPM_COMPONENT_INSTALL ON)

# DEB
set(CPACK_DEBIAN_PACKAGE_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_DEBUGINFO_PACKAGE OFF)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Alin Popa")
set(CPACK_DEBIAN_PACKAGE_SECTION "Utilities")
set(CPACK_DEBIAN_BIN_PACKAGE_DEPENDS "libprotobuf17 (>=3.0.0)")
set(CPACK_DEBIAN_DEV_PACKAGE_DEPENDS "${PROJECT_NAME}-bin (=${CPACK_DEBIAN_PACKAGE_VERSION}), libprotobuf17 (>=3.0.0), libprotobuf-dev (>=3.0.0), protobuf-compiler (>=3.0.0)")
set(CPACK_DEB_COMPONENT_INSTALL ON)

# FreeBSD
set(CPACK_FREEBSD_DEBUGINFO_PACKAGE OFF)
set(CPACK_FREEBSD_PACKAGE_MAINTAINER "Alin Popa")
set(CPACK_FREEBSD_PACKAGE_ORIGIN "devel/libtaskmonitor")
set(CPACK_FREEBSD_PACKAGE_DEPENDS "devel/protobuf")

include(CPack)
